project:
  type: website
  output-dir: docs

website:
  title: "Investing in AI - UKRI"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    search: true
    contents:
      - section: "Home"
        contents:
        - index.qmd
      - section: "Getting Data"
        contents:
         - 01.qmd
      - section: "Topic Model"
        contents:
         # - 04.qmd #topic model
         - 05.qmd
      - section: "Other Findings"
        contents:
         - 02.qmd #trend
         - 03.qmd #semetic

format:
  html:
    theme: cosmo
    code-fold: true
    toc: true
    df-print: paged