project:
  type: website

website:
  title: "Investing in AI - UKRI"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    search: true
    contents:
      - section: "Getting Data"
        contents:
         - 01.qmd
      - section: "Analysis"
        contents:
         - 02.qmd
         - 03.qmd

format:
  html:
    theme: cosmo
    code-fold: true
    toc: true
    df-print: paged